apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  secrets:
    scopes:
      - storeName: "kotlinkv"
#        defaultAccess: "deny"
        allowedSecrets: ["connectionStringtest",]
